baseURL = 'https://vectorsandverbs.com/'
languageCode = 'en-us'
title = 'Vectors & Verbs'
theme = 'papermod'

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  
  [params.homeInfoParams]
    Title = "Vectors & Verbs<span class=\"home-author\">by Siddhesh Inamdar</span>"
    Content = "Exploring the intersection of human creativity and machine intelligence."

  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/siddheshinamdar"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/siddhesh-inamdar-24634694/"
  [[params.socialIcons]]
    name = "medium"
    url = "https://medium.com/@siddheshnmdr"
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/SidInamdar"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"
    weight = 20
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 30
